### ISSUE TITLE
Code of model missing

### ISSUE THREAD

**Issue by walsvid** [IGLICT/OctField#1]
Hi, authors, thanks for your great work. I found that the implementation  of `models.RecursiveEncoder` is missing. It looks like the `models.py` file is missing.

**Comment by tangjiaheng** [comment]
Thanks for your attention to our work. Sorry, I accidentally deleted the file with log files because they have the same prefix. I have uploaded this [file](https://github.com/IGLICT/OctField/blob/main/model.py). If you have further problems, please feel free to contact us.
