### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zouwenqin** [IGLICT/OctField#2]
![image](https://user-images.githubusercontent.com/66156211/147475174-6e149f25-708c-4808-973a-b91385e2ab89.png)
可以提供数据集划分的txt文件吗

**Comment by zouwenqin** [comment]
代码部分有几处出现未定义的符号的小错误，如pkg_part.py中
![image](https://user-images.githubusercontent.com/66156211/147478067-447c09bf-70f9-4784-8b19-78b166b8b57f.png)

**Comment by tangjiaheng** [comment]
> 代码部分有几处出现未定义的符号的小错误，如pkg_part.py中 ![image](https://user-images.githubusercontent.com/66156211/147478067-447c09bf-70f9-4784-8b19-78b166b8b57f.png)

此处代码已更新

> ![image](https://user-images.githubusercontent.com/66156211/147475174-6e149f25-708c-4808-973a-b91385e2ab89.png) 可以提供数据集划分的txt文件吗

数据集划分已上传
