### ISSUE TITLE
Target file not found after compilation

### ISSUE THREAD

**Issue by xmeng525** [IGLICT/OctField#3]
Hi,
Thank you for releasing the code! :) 
I'm trying to run the code and I've successfully compiled imp_sampling. However, I cannot find the file "generateSamplesWind" after compilation and I cannot find any code related to generateSamplesWind in imp_sampling/build/Makefile.
https://github.com/IGLICT/OctField/blob/e776b3bc8a0abcf5c8d875cb679647fcaef33c36/imp_sampling/ReadMe.txt#L6
Would you please check this part?
Another question is: may I transform the .sdf file to a mesh directly? Would you please release the code if you have it? Thank you!

**Comment by tangjiaheng** [comment]
Sorry, the ReadMe here may be confusing. We have revised this part of the code, and now we do not directly generate .sdf file using generateSamplesWind. The compiled .so file will be used.
